---
latitude: 40.750613
longitude: -73.977095
map_zoom: 12
name: Oceans Edge Key West
email: info@oceansedgekeywest.com
phone_number: 123-123-1234
address:
  street1: 5950 Peninsular Avenue
  state: FL
  city: Key West
  zip_code: '33040'
default_currency: USD
default_timezone: America/New_York
_hotel_id: RAHUL
_portal_id: Rahul
__EDITABLE_FIELDS__:
  name:
    required: true
  logo:
    type: image
  email:
    type: string
  phone:
    type: string
  default_currency:
    required: true
  address:
    type: complex
    fields:
      street1:
        type: string
      state:
        type: string
      city:
        type: string
      zip_code:
        type: string
  google_location:
    type: location
  map_zoom:
    type: integer
  latitude:
    type: float
  longitude:
    type: float
phone: '3058098204'
logo:
  name: Oceans Edge Key West
  content_type: image/png
  date_added: 2019-10-23-082702
  url_thumb: "//res.cloudinary.com/traveltripperweb/image/upload/c_fill,g_faces,h_140,w_140/v1571833622/knl7o6dwlclsv52fryx2.png"
  url_xsmall: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_300,w_300/v1571833622/knl7o6dwlclsv52fryx2.png"
  url_small: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_768,w_768/v1571833622/knl7o6dwlclsv52fryx2.png"
  url_medium: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_992,w_992/v1571833622/knl7o6dwlclsv52fryx2.png"
  url_large: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_1200,w_1200/v1571833622/knl7o6dwlclsv52fryx2.png"
  url_xlarge: "//res.cloudinary.com/traveltripperweb/image/upload/c_limit,h_1920,w_1920/v1571833622/knl7o6dwlclsv52fryx2.png"
  url: "//res.cloudinary.com/traveltripperweb/image/upload/c_limit,h_2500,w_2500/v1571833622/knl7o6dwlclsv52fryx2.png"
  width: 240
  height: 97
  format: png
  url_raw: "//res.cloudinary.com/traveltripperweb/image/upload/v1571833622/knl7o6dwlclsv52fryx2.png"
  resource_type: image
  size: 6689
  path: "//res.cloudinary.com/traveltripperweb/image/upload/c_limit,h_2500,w_2500/v1571833622/knl7o6dwlclsv52fryx2.png"
  file_size: 
  alt: Oceans Edge Key West
  caption: ''
  description: ''
