---
latitude: 40.750613
longitude: -73.977095
map_zoom: 12
name: Oceans Edge Key West
email: info@oceansedgekeywest.com
phone_number: 305-809-8204
address:
  street1: 5950 Peninsular Avenue
  state: FL
  city: Key West
  zip_code: '33040'
default_currency: USD
default_timezone: America/New_York
_hotel_id: 4091
_chain_id: 10237
_portal_id:
booking_url: https://be.synxis.com/?hotel=4091&chain=10237
booking_link: https://be.synxis.com/
_root_path: https://rt3api-prd.ttaws.com
_ttweb_plugins_version: v3.5.0
__EDITABLE_FIELDS__:
  name:
    required: true
  logo:
    type: image
  logo-footer:
    type: image
  email:
    type: string
  phone:
    type: string
  booking_url:
    type: string
  default_currency:
    required: true
  address:
    type: complex
    fields:
      street1:
        type: string
      state:
        type: string
      city:
        type: string
      zip_code:
        type: string
  google_location:
    type: location
  map_zoom:
    type: integer
  latitude:
    type: float
  longitude:
    type: float
reservation: 877-935-0862
phone: '3058098204'
logo:
  name: Oceans Edge Key West
  content_type: image/png
  date_added: 2019-10-24-033607
  url_thumb: "//res.cloudinary.com/traveltripperweb/image/upload/c_fill,g_faces,h_140,w_140/v1571902567/ym5qpajryd261t5kot5s.png"
  url_xsmall: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_300,w_300/v1571902567/ym5qpajryd261t5kot5s.png"
  url_small: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_768,w_768/v1571902567/ym5qpajryd261t5kot5s.png"
  url_medium: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_992,w_992/v1571902567/ym5qpajryd261t5kot5s.png"
  url_large: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_1200,w_1200/v1571902567/ym5qpajryd261t5kot5s.png"
  url_xlarge: "//res.cloudinary.com/traveltripperweb/image/upload/c_limit,h_1920,w_1920/v1571902567/ym5qpajryd261t5kot5s.png"
  url: "//res.cloudinary.com/traveltripperweb/image/upload/c_limit,h_2500,w_2500/v1571902567/ym5qpajryd261t5kot5s.png"
  width: 1309
  height: 523
  format: png
  url_raw: "//res.cloudinary.com/traveltripperweb/image/upload/v1571902567/ym5qpajryd261t5kot5s.png"
  resource_type: image
  size: 85237
  path: "//res.cloudinary.com/traveltripperweb/image/upload/c_limit,h_2500,w_2500/v1571902567/ym5qpajryd261t5kot5s.png"
  file_size:
  alt: Oceans Edge Key West
  caption: ''
  description: ''
logo-footer:
  name: Oceans Edge Key West
  content_type: image/png
  date_added: 2019-10-28-204820
  url_thumb: "//res.cloudinary.com/traveltripperweb/image/upload/c_fill,g_faces,h_140,w_140/v1572310100/hy90tniffjeoxnnywfbg.png"
  url_xsmall: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_300,w_300/v1572310100/hy90tniffjeoxnnywfbg.png"
  url_small: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_768,w_768/v1572310100/hy90tniffjeoxnnywfbg.png"
  url_medium: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_992,w_992/v1572310100/hy90tniffjeoxnnywfbg.png"
  url_large: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_1200,w_1200/v1572310100/hy90tniffjeoxnnywfbg.png"
  url_xlarge: "//res.cloudinary.com/traveltripperweb/image/upload/c_limit,h_1920,w_1920/v1572310100/hy90tniffjeoxnnywfbg.png"
  url: "//res.cloudinary.com/traveltripperweb/image/upload/c_limit,h_2500,w_2500/v1572310100/hy90tniffjeoxnnywfbg.png"
  width: 221
  height: 89
  format: png
  url_raw: "//res.cloudinary.com/traveltripperweb/image/upload/v1572310100/hy90tniffjeoxnnywfbg.png"
  resource_type: image
  size: 3798
  path: "//res.cloudinary.com/traveltripperweb/image/upload/c_limit,h_2500,w_2500/v1572310100/hy90tniffjeoxnnywfbg.png"
  file_size:
  alt: Oceans Edge Key West
